### ISSUE TITLE
1 19 2 version?

### ISSUE THREAD

**Issue by DefomCode** [Mythos-Developers/Patchwork#1]
# mod for lower versions
Will there be a mod for lower versions? it's just that most of the mods I need are now on 1.19.2, and on 1.20.1 they either don't exist or they are not stable.

I need this mod on 1.19.2

**Comment by ScienceMind11** [comment]
Oh my gosh I'm so sorry I didn't check this earlier lmao

I'll try to get that out as soon as I can with hs and stuff. Sorry!

**Comment by ScienceMind11** [comment]
Alright, created a branch for this (should've been done from the beginning)

**Comment by ScienceMind11** [comment]
While I'm at it, I'll throw in some more stuff if I can. Any suggestions?

**Comment by ScienceMind11** [comment]
Okay, over a month since the request and it's almost done. @DefomCode, just FYI.

**Comment by ScienceMind11** [comment]
Should be available on Modrinth now! Link [here](https://modrinth.com/mod/patchwork-quilt/version/0.3.1+1.19.2).
